/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    int x = 2;
    int y = 3;
    System.out.println(new App().getGreeting());

    System.out.print("Sum of " + x + " and " + y + " is " + new Calculate().sum(x, y) + ". ");
    System.out.println("Average is " + new Calculate().sumave(x, y) + ".");

    System.out.print("Sum of 0 to 10 is " + new Calculate().sum10() + ". ");
    System.out.println("Average is " + new Calculate().sum10ave() + ".");

    System.out.print("Sum of odd of 1 to 10 is " + new Calculate().sumOdd10() + ". ");
    System.out.print("Sum of even is " + new Calculate().sumEven10() + ". ");
  }
}
