/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

  // public void appHasAGreeting() {
  // App classUnderTest = new App();
  // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  // }

  // public void testAppReternHelloWorld() {
  // App classUnderTest = new App();
  // assertEquals("Hello World!", classUnderTest.getGreeting());
  // /* "Hello World!" -> "Hello World"に変更 */
  // }

  @Test
  public void testAppReternHello() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
    /* "Hello World!" -> "Hello World"に変更 */
  }
}
